[package]
name = "moe-sdk"
version = "1.3.6"
edition = "2024"
description = "Unified entrypoint for MoE-13 ecosystem."
license = "LGPL-3.0-or-later"
repository = "https://github.com/eriirfos-eng/ternary-intelligence-stack"

[dependencies]
moe-platform = { path = "../moe-platform", version = "1.3.6" }
moe-plugin-sdk = { path = "../moe-plugin-sdk", version = "1.3.6" }
