[package]
name = "ternlang-driver"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ternlang-core = { path = "../compiler/legacy_shim/ternlang-core", version = "1.0.0" }
