name: 'TIS Auditor: Thermal Waste Scanner'
description: 'Identify binary inefficiencies and thermal waste in legacy codebases (v0.1.1).'
author: 'RFI-IRFOS'
version: 'v0.1.1'
inputs:
  path:
    description: 'Project path to scan'
    required: false
    default: '.'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'search'
  color: 'green'
