[package]
name        = "ternlang-core"
description = "Post-Quantum Balanced Ternary Core. Native Sparsity for 60% Power Reduction. The definitive BET VM implementation."
version.workspace   = true
edition.workspace   = true
license.workspace   = true
repository.workspace = true
homepage.workspace  = true
authors.workspace   = true
keywords.workspace  = true
categories.workspace = true

[dependencies]
ariadne = "0.6.0"
logos = "0.16.1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
rand = "0.8"
