[workspace]
members = [
    "compiler/legacy_shim/ternlang-core",
    "compiler/legacy_shim/ternlang-codegen",
    "compiler/legacy_shim/ternlang-runtime",
    "compiler/legacy_shim/ternlang-cli",
    "ternlang-ml",
    "ternlang-api",
    "ternlang-test",
    "ternlang-mcp",
    "ternlang-hdl",
    "ternlang-lsp",
    "ternpkg",
    "ternlang-compat",
    "ternlang-moe",
]
resolver = "2"

[workspace.package]
version     = "0.3.0"
edition     = "2024"
license     = "LGPL-3.0-or-later"
repository  = "https://github.com/eriirfos-eng/ternary-intelligence-stack"
homepage    = "https://ternlang.com"
authors     = ["RFI-IRFOS <licensing@ternlang.com>"]
keywords    = ["ternary", "trit", "balanced-ternary", "vm", "compiler"]
categories  = ["compilers", "science"]
